repos:
  # Let's go with local in the absence of an actively maintained pre-commit hook for Zola.
  - repo: local
    hooks:
      - id: zola-check
        name: Check Zola website
        entry: zola check
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        name: Check YAML files
      - id: check-toml
        name: Check TOML files
      - id: check-json
        name: Check JSON files
      - id: destroyed-symlinks
        name: Check for broken symlinks
      - id: detect-private-key
        name: Detect private keys
      - id: mixed-line-ending
        name: Check for mixed line endings
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: end-of-file-fixer
        name: Fix end of files
      - id: trailing-whitespace
        name: Trim trailing whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.22.0
    hooks:
      - id: markdownlint-cli2
        name: Markdown Lint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: YAML Lint
        args: ["-c", ".yamllint"]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks
